export const ActionTypes = {
  DISPLAY_TOOLTIP: "DISPLAY_TOOLTIP",
  CHANGE_TOTAL_PRICE: "CHANGE_TOTAL_PRICE",
  ITEM_DISPLAY_MODE: "ITEM_DISPLAY_MODE",
  DISCOUNT_DISPLAY_MODE: "DISCOUNT_DISPLAY_MODE",
  APPLY_DISCOUNT: "APPLY_DISCOUNT",
  INPUT_DISCOUNT: "INPUT_DISCOUNT"
};
